// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1frUEVf74w63VN4q-KvFpXenSLS_u5fQ',
    appId: '1:250726143244:web:4a8c895f4ecce4bf622529',
    messagingSenderId: '250726143244',
    projectId: 'booking-f1036',
    authDomain: 'booking-f1036.firebaseapp.com',
    storageBucket: 'booking-f1036.appspot.com',
    measurementId: 'G-HS5WWRBXDJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmMUlbV-kitX2YlLlfX8j24WN6TgeKJ6A',
    appId: '1:250726143244:android:57a76aaec90471e8622529',
    messagingSenderId: '250726143244',
    projectId: 'booking-f1036',
    storageBucket: 'booking-f1036.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDej5U3RcdrAN_1wYbn2VLiuKyTtPsTfLI',
    appId: '1:250726143244:ios:812f2079731ea9ca622529',
    messagingSenderId: '250726143244',
    projectId: 'booking-f1036',
    storageBucket: 'booking-f1036.appspot.com',
    iosBundleId: 'com.example.roome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDej5U3RcdrAN_1wYbn2VLiuKyTtPsTfLI',
    appId: '1:250726143244:ios:b57a2c3f82005f12622529',
    messagingSenderId: '250726143244',
    projectId: 'booking-f1036',
    storageBucket: 'booking-f1036.appspot.com',
    iosBundleId: 'com.example.roome.RunnerTests',
  );
}
